### PR TITLE
add cal::realtive_duration support

### PR DESCRIPTION
**Pull request by fmoor**

### CODE REVIEW

**Comment by fmoor** [comment]
WIP until https://github.com/edgedb/edgedb/pull/2559 is merged.

**Comment by 1st1** [comment]
Looks like we've totally forgotten about this one. @fmoor let's revive it; please rebase, and let @jaclarke and I when this is ready to review.

James, please check if the `RelativeDuration` type this PR adds conforms to the temporal spec.

**Comment by fmoor** [comment]
ready for review @jaclarke @1st1

**Comment by jaclarke** [comment]
> James, please check if the RelativeDuration type this PR adds conforms to the temporal spec.

`cal::relative_duration` doesn't quite map to any type in the temporal spec. The closest is `Temporal.Duration`, it has the same fields as `cal::relative_duration` (plus `weeks` and `nanoseconds` fields) and has the same semantic meaning, but it seems `cal::relative_duration` accepts fields with mixed signs and `Temporal.Duration` doesn't.

**Comment by 1st1** [comment]
>  accepts fields with mixed signs

Can you elaborate on this? Like when years is a positive number and weeks is a negative one? But it's happy if all are negative at the same time?

**Comment by jaclarke** [comment]
> Like when years is a positive number and weeks is a negative one? But it's happy if all are negative at the same time?

Yes, this is allowed in edgedb:
```edgeql
edgedb> SELECT cal::to_relative_duration(months := 3, days := -4);
{<cal::relative_duration>'P3M-4D'}
```
but not in `Temporal.Duration`:
```js
new Temporal.Duration(0, 3, 0, -4);
// Uncaught RangeError: mixed-sign values not allowed as duration fields
```
If all the non-zero fields are negative then it's ok:
```js
new Temporal.Duration(0, -3, 0, -4);
// Object {
//  _repr_: "Temporal.Duration <-P3M4D>"
// ...
```

**Review by 1st1 — APPROVED** [review]

**Pull request merged**
