### PR TITLE
Fix error message and doc example

### PR DESCRIPTION
**Pull request by cosmophile**
Congrats on shipping Alpha 2!

### CODE REVIEW

**Comment by 1st1** [comment]
Thank you!

Btw, I'm quite curious about what you are building with EdgeDB :)

**Comment by cosmophile** [comment]
Hi Yury! I'm a full-stack/master-of-none/run-of-the-mill developer writing endless crud apps with just enough variations to find the energy to have the same client conversations over and over again. In that line of work I use some of the popular solutions out there, usually a combination of MariaDB, Redis and ElasticSearch. 

edgedb is the first database that has made me, a total db dilettante, feel powerful and expressive, and like I am getting a glimpse of why people geek out over databases - its a bit like having a superpower! I've taken up a couple of side projects because I'm eager to fully imbibe the possibilities of this db and I can only get that by endlessly hacking on the repl at this stage. But the language is so fun to write, it feels like chatting with AI 😉 

To answer your question: so far just a simple dashboard for a friend. But soon: all the things! With Alpha2 I am keen to see if I can build myself a visual query builder, at least for my everyday work, at the very least for quick prototyping. 

Also, merch. I need EdgeQL queries on a t-shirt, or a "I <3 edgedb" coffee mug at the very least.

**Comment by 1st1** [comment]
Thanks for the kind feedback, things like "the language is so fun to write, it feels like chatting with AI" really encourage us to push forward!  Please feel free to share more of your findings / feature requests about EdgeQL/docs/drivers with us!

**Comment by 1st1** [comment]
Also we're quite active in https://spectrum.chat/edgedb -- if you have a question or just want to have a quick chat with us.

**Comment by 1st1** [comment]
Lastly, could you please shoot me an email at yury@edgedb.com?

**Pull request merged**
